### ISSUE TITLE
Первый слайд должен автоматически подстраиваться под высоту браузера

### ISSUE THREAD

**Issue by deepseer88** [deepseer-gsi/office365Promo#1]

**Comment by Yulia-a** [comment]
На моем ноутбуке первый слайд не выравнивается на всю высоту монитора. Внизу полоска остается.
![image](https://cloud.githubusercontent.com/assets/11875053/14739161/6e63cd82-088e-11e6-9194-75856173f409.png)

**Comment by darinawinner** [comment]
Юль, ты помнишь, я просила помочь с этим скриптом? Он есть в файле js, даже 2 закомментированных, но они работают неправильно и почему - непонятно.

**Comment by Yulia-a** [comment]
Замени <html lang="en"> на <!DOCTYPE html> и убери свойство для #header  { padding-top: 11%; }. Тогда последний скрипт работает корректно. Нужно будет только отцентрировать содержимое в #header  

function setheight(){

```
var theWindow = $(window).height();

$('#header').height(theWindow);

//alert("monitorHeight: " + theWindow);

}



$(window).load(function() {

setheight();

});



$(window).resize(function(){

setheight();

});
```

**Comment by darinawinner** [comment]
Поняла. Спасибо большое!
