### ISSUE TITLE
Меню в мобильной версии подправить

### ISSUE THREAD

**Issue by Yulia-a** [deepseer-gsi/office365Promo#13]

**Comment by darinawinner** [comment]
что именно?

**Comment by Yulia-a** [comment]
Отступы (оранжевые) вверху и по бокам лишние. На сайте оригинале меню справа появляется. Но можно сделать хотя бы так как у Саши http://deepseer-gsi.github.io/office365/
![image](https://cloud.githubusercontent.com/assets/11875053/14634337/2e7bf804-062a-11e6-8912-b20eea260ce7.png)

**Comment by Yulia-a** [comment]
на сайте оригинале так:
![image](https://cloud.githubusercontent.com/assets/11875053/14634534/01d9ee40-062b-11e6-9430-39382a36f2cc.png)

**Comment by Yulia-a** [comment]
Плюс кнопка прокрутки должна быть снизу или вообще убирать ее на мобильных девайсах (<768px)

**Comment by darinawinner** [comment]
поняла
